### ISSUE TITLE
Container cannot bind to port 80 and 443

### ISSUE THREAD

**Issue by sidharthramesh** [openfaas/faasd#182]
Excellent project here. Just read the book 'Serverless for Everyone Else' and trying to integrate my project into faasd.

## Expected Behaviour

Additional container in `/var/lib/faasd/docker-compose.yaml` should be able to bind to port 80 and 443. 

## Current Behaviour

I have caddy running inside a container along with the other faasd services:
```
caddy:
    image: docker.io/library/caddy:2.4.1
    user: "1007"
    ports:
      - "127.0.0.1:2019:2019"
      - "80:80"
      - "443:443"
    cap_add:
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    volumes:
      - ./medblocks/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./medblocks/caddy/data:/data
      - ./medblocks/caddy/config:/config
```
Caddy is unable to bind to port 80, or any other low numbered ports. I have added the `CAP_NET_BIND_SERVICE` under the `cap_add` since I thought that might help.
Error logs from `journalctl -t openfaas:caddy`
```
Jun 23 13:17:07 test2 openfaas:caddy[6345]: {"level":"info","ts":1624434427.8451076,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
Jun 23 13:17:07 test2 openfaas:caddy[6345]: {"level":"warn","ts":1624434427.8497114,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
Jun 23 13:17:07 test2 openfaas:caddy[6345]: {"level":"info","ts":1624434427.8537989,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["[::1]:2019","127.0.0.1:2019","localhost:2019"]}
Jun 23 13:17:07 test2 openfaas:caddy[6345]: {"level":"info","ts":1624434427.8544886,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
Jun 23 13:17:07 test2 openfaas:caddy[6345]: {"level":"info","ts":1624434427.8596344,"logger":"tls","msg":"cleaning storage unit","description":"FileStorage:/data/caddy"}
Jun 23 13:17:07 test2 openfaas:caddy[6345]: {"level":"info","ts":1624434427.8605876,"logger":"tls","msg":"finished cleaning storage units"}
Jun 23 13:17:07 test2 openfaas:caddy[6345]: {"level":"info","ts":1624434427.8614266,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000262850"}
Jun 23 13:17:07 test2 openfaas:caddy[6345]: {"level":"info","ts":1624434427.8614473,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc000262850"}
Jun 23 13:17:07 test2 openfaas:caddy[6345]: run: loading initial config: loading new config: http app module: start: tcp: listening on :80: listen tcp :80: bind: permission denied
```
Might be related to https://github.com/containerd/containerd/issues/2516

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [x] No

## List all Possible Solutions
I could just run caddy as a system service instead of a container, however, I want to access the other services and I want other services to change the configuration of caddy during run time.

## Steps to Reproduce (for bugs)

1. Set an ubuntu instance on multipass.
2. Install faasd
3. Use this docker-compose.yaml
```
version: "3.7"
services:
  basic-auth-plugin:
    image: ghcr.io/openfaas/basic-auth:0.20.12
    environment:
      - port=8080
      - secret_mount_path=/run/secrets
      - user_filename=basic-auth-user
      - pass_filename=basic-auth-password
    volumes:
      # we assume cwd == /var/lib/faasd
      - type: bind
        source: ./secrets/basic-auth-password
        target: /run/secrets/basic-auth-password
      - type: bind
        source: ./secrets/basic-auth-user
        target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW

  nats:
    image: docker.io/library/nats-streaming:0.11.2
    command:
      - "/nats-streaming-server"
      - "-m"
      - "8222"
      - "--store=memory"
      - "--cluster_id=faas-cluster"
    # ports:
    #    - "127.0.0.1:8222:8222"

  prometheus:
    image: docker.io/prom/prometheus:v2.14.0
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    cap_add:
      - CAP_NET_RAW
    ports:
       - "127.0.0.1:9090:9090"

  gateway:
    image: ghcr.io/openfaas/gateway:0.20.12
    environment:
      - basic_auth=true
      - functions_provider_url=http://faasd-provider:8081/
      - direct_functions=false
      - read_timeout=60s
      - write_timeout=60s
      - upstream_timeout=65s
      - faas_nats_address=nats
      - faas_nats_port=4222
      - auth_proxy_url=http://basic-auth-plugin:8080/validate
      - auth_proxy_pass_body=false
      - secret_mount_path=/run/secrets
      - scale_from_zero=true
      - function_namespace=openfaas-fn
    volumes:
      # we assume cwd == /var/lib/faasd
      - type: bind
        source: ./secrets/basic-auth-password
        target: /run/secrets/basic-auth-password
      - type: bind
        source: ./secrets/basic-auth-user
        target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW
    depends_on:
      - basic-auth-plugin
      - nats
      - prometheus
    ports:
       - "8080:8080"

  queue-worker:
    image: docker.io/openfaas/queue-worker:0.11.2
    environment:
      - faas_nats_address=nats
      - faas_nats_port=4222
      - gateway_invoke=true
      - faas_gateway_address=gateway
      - ack_wait=5m5s
      - max_inflight=1
      - write_debug=false
      - basic_auth=true
      - secret_mount_path=/run/secrets
    volumes:
      # we assume cwd == /var/lib/faasd
      - type: bind
        source: ./secrets/basic-auth-password
        target: /run/secrets/basic-auth-password
      - type: bind
        source: ./secrets/basic-auth-user
        target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW

  caddy:
    image: docker.io/library/caddy:2.4.1
    user: "1007"
    ports:
      - "127.0.0.1:2019:2019"
      - "80:80"
      - "443:443"
    cap_add:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
```
4. Check the logs at `sudo journalctl -t openfaas:caddy -f`

## Context

I'm trying to setup an installation script for faasd with other open-source healthcare tools - [medblocks-faasd](https://github.com/medblocks/medblocks-faasd). Having caddy as a service within the openfaas stack will be nice.

## Your Environment

* OS and architecture: Windows 10 running multipass.

* Versions:

```sh
go version
Not installed

containerd -version
containerd github.com/containerd/containerd v1.3.7 8fba4e9a7d01810a393d5d25a3621dc101981175

uname -a
Linux test2 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

faasd version
faasd version: 0.11.4   commit: dca036ee51a7275389bf45c7839d22d437663a8e
```
