### ISSUE TITLE
Support request for custom configuration

### ISSUE THREAD

**Issue by Aschen** [openfaas/faasd#183]
## Expected Behaviour

Running faasd by using the `docker-compose.yml` file should allows me to list functions.

```
faas-cli list
```

## Current Behaviour

Trying to list functions (and any other API action) returns a 502 error:
```
 faas-cli list
Server returned unexpected status code: 500 - List functions responded with code 502
```

In Docker-compose logs I can see I failing call to a local DNS `dial tcp: lookup faasd-provider on 127.0.0.11:53: no such host`

```
gateway_1       | 2021/06/24 05:38:16 Forwarded [GET] to /system/functions - [502] - 0.002857s seconds
gateway_1       | 2021/06/24 05:38:16 List functions responded with code 502, body: 
gateway_1       | 2021/06/24 05:38:17 error with upstream request to: /system/functions, Get "http://faasd-provider:8081/system/functions": dial tcp: lookup faasd-provider on 127.0.0.11:53: no such host
gateway_1       | 2021/06/24 05:38:17 Forwarded [GET] to /system/functions - [502] - 0.002342s seconds
gateway_1       | 2021/06/24 05:38:17 List functions responded with code 502, body: 
gateway_1       | 2021/06/24 05:38:17 Get "http://faasd-provider:8081/system/namespaces": dial tcp: lookup faasd-provider on 127.0.0.11:53: no such host
gateway_1       | 2021/06/24 05:38:17 Get "http://faasd-provider:8081/system/functions?namespace=openfaas-fn": dial tcp: lookup faasd-provider on 127.0.0.11:53: no such host
```

## Are you a GitHub Sponsor (Yes/No?)

Check at: https://github.com/sponsors/openfaas
- [ ] Yes
- [X] No

## Steps to Reproduce (for bugs)

I had to modify the docker compose to disable the basic-auth plugin and run the nats-streaming service

1. Save this file as docker-compose-mod.yml

<details><summary>docker-compose.yml</summary>

```
version: "3.7"
services:
  # basic-auth-plugin:
    # image: ghcr.io/openfaas/basic-auth:0.20.12
    # environment:
    #   - port=8080
    #   - secret_mount_path=/run/secrets
    #   - user_filename=basic-auth-user
    #   - pass_filename=basic-auth-password
    # volumes:
    #   # we assume cwd == /var/lib/faasd
    #   - type: bind
    #     source: ./secrets/basic-auth-password
    #     target: /run/secrets/basic-auth-password
    #   - type: bind
    #     source: ./secrets/basic-auth-user
    #     target: /run/secrets/basic-auth-user
    # cap_add:
    #   - CAP_NET_RAW

  nats:
    image: docker.io/library/nats-streaming:0.11.2
    command: "--store=memory --cluster_id=faas-cluster"
      # - "/nats-streaming-server"
      # - "--store=memory"
      # - "--cluster_id=faas-cluster"
    ports:
       - "127.0.0.1:8222:8222"

  prometheus:
    image: docker.io/prom/prometheus:v2.14.0
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml
    cap_add:
      - CAP_NET_RAW
    ports:
       - "127.0.0.1:9090:9090"

  gateway:
    image: ghcr.io/openfaas/gateway:0.20.12
    environment:
      # - basic_auth=true
      - functions_provider_url=http://faasd-provider:8081/
      - direct_functions=false
      - read_timeout=60s
      - write_timeout=60s
      - upstream_timeout=65s
      - faas_nats_address=nats
      - faas_nats_port=4222
      # - auth_proxy_url=http://basic-auth-plugin:8080/validate
      # - auth_proxy_pass_body=false
      - secret_mount_path=/run/secrets
      - scale_from_zero=true
      - function_namespace=openfaas-fn
    # volumes:
      # we assume cwd == /var/lib/faasd
      # - type: bind
      #   source: ./secrets/basic-auth-password
      #   target: /run/secrets/basic-auth-password
      # - type: bind
      #   source: ./secrets/basic-auth-user
      #   target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW
    depends_on:
      # - basic-auth-plugin
      - nats
      - prometheus
    ports:
       - "8080:8080"

  queue-worker:
    image: docker.io/openfaas/queue-worker:0.11.2
    environment:
      - faas_nats_address=nats
      - faas_nats_port=4222
      - gateway_invoke=true
      - faas_gateway_address=gateway
      - ack_wait=5m5s
      - max_inflight=1
      - write_debug=false
      # - basic_auth=true
      # - secret_mount_path=/run/secrets
    # volumes:
    #   # we assume cwd == /var/lib/faasd
    #   - type: bind
    #     source: ./secrets/basic-auth-password
    #     target: /run/secrets/basic-auth-password
    #   - type: bind
    #     source: ./secrets/basic-auth-user
    #     target: /run/secrets/basic-auth-user
    cap_add:
      - CAP_NET_RAW
    depends_on:
      - nats
```

</details>

2. Run `docker-compose up -f docker-compose-mod.yml`
3. In another terminal, run `faas-cli list`

## Context

I'm trying to run OpenFaas with Docker Compose

## Your Environment

* OS and architecture:

Manjaro Linux

* Versions:

```sh
$ faas-cli version

CLI:
 commit:  72816d486cf76c3089b915dfb0b66b85cf096634
 version: 0.13.13

Gateway
 uri:     http://127.0.0.1:8080
 version: 0.20.12
 sha:     a6dbb4cd0285f6dbc0bc3f43f72ceacdbdf6f227

```
