### ISSUE TITLE
Validate docker-compose.yaml file with arkade chart verify

### ISSUE THREAD

**Issue by alexellis** [openfaas/faasd#302]
Validate docker-compose.yaml file with the `arkade chart verify` command

## Why do you need this?

Sometimes invalid images tags could be put into the faasd compose file.

The change may be to go one level deeper in the struct:

```yaml
# 1
image:

# 2
component.image:

# 3
services:
  component:
    image:
```
