### ISSUE TITLE
502 error faasd gateway timeout at 60 seconds for async function with webhook

### ISSUE THREAD

**Issue by unnimona** [openfaas/faasd#305]
**Expected behaviour** 
my aim is that function to return 200 OK with output even if it takes any time with maybe at the maximum time of 10 minutes and not 60 seconds

**Current Behaviour**

i made a function but i observed if the processing takes more than 60 seconds results in 502 error with no output. I can see in the function logs that function successfully completed at Duration: 192s
I had also set      write_debug: true in stack.yml as a result I can see the output of function and the function has run sucessfully. 

#function log  
```
2022-09-18T23:52:36Z 2022/09/18 23:52:36 Duration: 192.188893s
2022-09-18T23:53:58Z 2022/09/18 23:53:58 SIGTERM: no new connections in 30s
2022-09-18T23:53:58Z 2022/09/18 23:53:58 Removing lock-file : /tmp/.lock
2022-09-18T23:54:29Z 2022/09/18 23:54:29 Version: 0.2.1 SHA: cd8dc9f4e98049150d8079a74a18cd5a2e311aeb
2022-09-18T23:54:29Z 2022/09/18 23:54:29 Timeouts: read: 5m0s write: 5m30s hard: 5m0s health: 30s.
2022-09-18T23:54:29Z 2022/09/18 23:54:29 Listening on port: 8080
2022-09-18T23:54:29Z 2022/09/18 23:54:29 Writing lock-file to: /tmp/.lock
2022-09-18T23:54:29Z 2022/09/18 23:54:29 Metrics listening on port: 8081
2022-09-18T23:55:04Z 2022/09/18 23:55:04 Forking fprocess.
2022-09-18T23:55:04Z 2022/09/18 23:55:04 Query
2022-09-18T23:55:04Z 2022/09/18 23:55:04 Path /
2022-09-18T23:56:51Z 2022/09/18 23:56:51 Forking fprocess.
2022-09-18T23:56:51Z 2022/09/18 23:56:51 Query
2022-09-18T23:56:51Z 2022/09/18 23:56:51 Path /
```

#webhook  output
```
content-length:
0
user-agent:
Go-http-client/1.1
date:
Sun, 18 Sep 2022 13:42:23 GMT
x-call-id:
6d3ecd63-661f-4b58-9542-fdbc17b8e092
x-duration-seconds:
60.014252
x-function-name:
yooyo
x-function-status:
502
x-start-time:
1663508483630221853
accept-encoding:
gzip
body:
```

Please tell me how to fix it?

**Are you a GitHub Sponsor (Yes/No?)**

 **NO**

**List all Possible Solutions**

I tried adding this to stack.yml  still no luck
```
    environment:
      write_timeout: 5m30s
      read_timeout: 5m
      exec_timeout: 5m
      handler_wait_duration: 1m30s
      healthcheck_interval: 30s

```

I also modified /var/lib/faasd/docker-compose.yaml   gateway 
```
  gateway:
    image: ghcr.io/openfaas/gateway:0.22.0
    environment:
      - basic_auth=true
      - functions_provider_url=http://faasd-provider:8081/
      - direct_functions=false
      - read_timeout=5m
      - write_timeout=5m30s
      - upstream_timeout=200s
      - faas_nats_address=nats
      - faas_nats_port=4222
      - auth_proxy_url=http://basic-auth-plugin:8080/validate
      - auth_proxy_pass_body=false
      - secret_mount_path=/run/secrets
      - scale_from_zero=true
      - function_namespace=openfaas-fn

 queue-worker:
    image: ghcr.io/openfaas/queue-worker:0.12.2
    environment:
      - faas_nats_address=nats
      - faas_nats_port=4222
      - gateway_invoke=true
      - faas_gateway_address=gateway
      - ack_wait=5m5s
      - max_inflight=1
      - write_debug=true
      - basic_auth=true
      - secret_mount_path=/run/secrets
      - faas_max_reconnect=120
      - faas_reconnect_delay=2s

```

 
**Steps to Reproduce (for bugs)**

Run a long process that executes greater than 60 seconds 

echo -n "input_data" | faas-cli invoke -f stack.yml

Output

**Your Environment**

go version
go version go1.18.1 linux/amd64

containerd -version
containerd github.com/containerd/containerd v1.6.8 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6

Linux avm 5.15.0-47-generic #51-Ubuntu SMP 2022 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

faasd version
  __                     _ 
 / _| __ _  __ _ ___  __| |
| |_ / _` |/ _` / __|/ _` |
|  _| (_| | (_| \__ \ (_| |
|_|  \__,_|\__,_|___/\__,_|

faasd version: 0.16.5   commit: 6b6ff71c29bb92df520541f8d51124dc3df14da6
