### ISSUE TITLE
Inter-function Communication Feature Asking

### ISSUE THREAD

**Issue by DanielLee343** [openfaas/faasd#316]
Hi, Alex. Thanks for the clear guide on faasd!

 I'm wondering if there's a feature for payload/data be transferred between functions, similar to [OpenWhisk’s Action Sequence](https://github.com/apache/openwhisk/blob/master/docs/actions.md), [Fn flow](https://github.com/fnproject/flow), or [AWS Step Functions](https://aws.amazon.com/step-functions/)?

Say I have a `stack.yml` as follows
```
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  fn1:
    lang: go
    handler: ./fn1
    image: fn1:latest
  fn2:
    lang: go
    handler: ./fn2
    image: fn2:latest
```
And each function is invoked by `curl`. I would like to feed fn2 with fn1's response body, or even send http request during function runtime (although not a best practice). I haven't found such feature in OpenFaaS documents. If any, is it relative to the architecture (Kubernetes/faasd)? Could you suggest any general best practices for multi-function communication in OpenFaaS? I appreciate that!
